version: '3'
services:

        # Database for the project
        db:
                # Use MySql 5 image for best compatability
                build: ./db

                # Set the port to the default port for MYSQL and expose to same host port
                ports:
                        - "3306:3306"

                # Try to restart container if it crashes or stops
                restart: always


        # Web server for dev files
        www:
                # Reference the dockerfile in the server directory for build instructions
                build: ./server

                # Set the host port to 8080 and link it with port 80 in the container
                ports:
                        - "8080:80"

                # Attach volume locally to html folder in container for active development
                # Add command to copy application files in build file when using on server
                volumes:
                        - ./server/app:/var/www/html
                
                # Wait for the database to spin up
                depends_on:
                        - db

                # Try to restart container if it crashes or stops
                restart: always
        

        # Admin tools for the above database
        phpmyadmin:          
                # Use the latest phpmyadmin image
                image: phpmyadmin:latest

                # Set the host port to 8081 and link it with port 80 in the container
                ports:                  
                        - "8081:80"

                # Wait for the server to spin up
                depends_on:
                        - www
                
                # Try to restart container if it crashes or stops
                restart: always