version: '3'
services:

        # Database for the project
        db:
                # Use MySql 5 image for best compatability
                image: mysql:5

                # Set the port to the default port for MYSQL and expose to same host port
                ports:
                        - "3306:3306"
                        
                # Set the default root password for host access
                environment:
                        MYSQL_ROOT_PASSWORD: "password"

                # Run startup scripts to fill databases with required data. Put any .sql load scripts you want to run in the startup_scripts folder
                volumes:
                        - ./startup_scripts:/docker-entrypoint-initdb.d/

                # Try to restart container if it crashes or stops
                restart: always


        # Admin tools for the above database
        phpmyadmin:          
                # Use the latest phpmyadmin image
                image: phpmyadmin:latest

                # Set the host port to 8081 and link it with port 80 in the container
                ports:                  
                        - "8081:80"
                
                # Try to restart container if it crashes or stops
                restart: always


        # Web server for dev files
        www:
                # Reference the dockerfile in the server directory for build instructions
                build: ./server

                # Set the host port to 8080 and link it with port 80 in the container
                ports:
                        - "8080:80"

                # Attach volume locally to html folder in container for active development
                # Add command to copy application files in build file when using on server
                volumes:
                        - ./server/app:/var/www/html
                
                # Try to restart container if it crashes or stops
                restart: always
        
